name: Build CyberLikh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore "CyberLikh.sln"

      - name: Build
        run: dotnet build "CyberLikh.sln" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "CyberLikh.csproj" -c Release -o publish

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: CyberLikh
          path: publish
